server:
  port: 8082

spring:
  application:
    name: product-ha


  datasource:
    url: jdbc:mysql://localhost:3306/eshop?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query:  select 'x' from dual



#mybatis相关配置
mybatis:
  type-aliases-package:  com.young.eshop.product.ha.model
  mapper-locations: classpath:com/young/eshop/product/ha/mapper/mapping/*Mapper.xml


#log记录
logging:
  path: /var/log/young/${spring.application.name}
  level:
    com.young: DEBUG
    org.springframework.boot.actuate.endpoint: WARN
    org.springframework.web.servlet.mvc.method.annotation: WARN


